language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*
    - SYMFONY_VERSION=dev-master

allow_failures:
    - php: hhvm

before_script:
    - composer require --prefer-source --dev symfony/symfony:${SYMFONY_VERSION}

script: phpunit --coverage-text

cache:
    directories:
        - $COMPOSER_CACHE_DIR
